[package]
name = "town-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
petgraph = "0.7"
strum = "0.26"
strum_macros = "0.26"
itertools = "0.14"
