seed = "Generate"
num_of_towns = 15
num_of_connections = 20
min_distance = 10
max_distance = 100
cost = 5
min_id = 1
max_id = 100000
min_buildings = 5
max_buildings = 25
min_npcs = 2
max_npcs = 10
min_rooms = 2
max_rooms = 6
min_containers = 0
max_containers = 4
input_dir = "input"
output_dir = "output"
